parameters:
#    miviaje_main.example.class: Miviaje\MainBundle\Example

services:
#    miviaje_main.example:
#        class: %miviaje_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  miviaje_service.oAuth:
    class:  Miviaje\MainBundle\Services\OAuthService